from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path
from typing import Protocol


@dataclass(frozen=True)
class StorageStat:
    size: int
    mtime: float


class Storage(Protocol):
    def iter_keys(self) -> Iterator[str]: ...
    def read(self, key: str) -> bytes: ...
    def write(self, key: str, data: bytes) -> None: ...
    def delete(self, key: str) -> None: ...
    def exists(self, key: str) -> bool: ...
    def stat(self, key: str) -> StorageStat: ...
    def local_path(self, key: str) -> Path | None: ...
    def free_bytes(self) -> int: ...
